# Generated by Django 3.2.8 on 2021-10-08 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangorestAPIapp', '0002_auto_20211008_1710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='products',
            new_name='category',
        ),
    ]
